### PR TITLE
automated command discovery

### PR DESCRIPTION
**Pull request by danthe1st**
[guide]: https://github.com/DuncteBot/SkyBot/wiki/Structure-Guide

Pull Request Etiquette
---

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [structure guide][guide].

Fixes NaN

- [X] I have tested my changes.
- [ ] I didn't test my changes. I will do that in the following 7 days and agree that this Pull request will be closed if I don't test it in the named time span.
- [X] I know the language good enough for providing high-quality code.

Description
---

This pull request uses the library `Reflection` in order to automatically scan the bot for commands and register them.

This removes the need for declaring every command individually and the same code does not have to be repeated over and over.

### CODE REVIEW

**Review by duncte123 — CHANGES_REQUESTED** [review]
1. Use the development Branch
2. This formatting is not consistent with the other code in the bot
3. This is something I've decided against as I don't want a library included just to scan some packages
4. Why the useless logger checks?

**Comment by duncte123** [comment]
FYI https://github.com/DuncteBot/SkyBot/pull/229/commits/2178eff5fa66315172a66574f445dda323e4cdf1

**Comment by danthe1st** [comment]
1. I did not find a note for the development branch in the contribunting guidelines or the structure guide (I will fix that, however)
2. What formatting did you mean, exactly?
3. Another option would be doing this at compile-time using a processor.
4. Because the logging called a method and this is only required if the logging is active (That would not make a difference in that case)

**Comment by duncte123** [comment]
With formatting I mean your code style
And being explicit about what commands are registered is better imo since it doesn't log about 100 warnings about unused classes

**Comment by danthe1st** [comment]
> And being explicit about what commands are registered is better imo since it doesn't log about 100 warnings about unused classes
It is possible to generate a class doing those explicitely at compile time what should remove the warnings.
> With formatting I mean your code style
What exactly?

**Comment by duncte123** [comment]
> It is possible to generate a class doing those explicitely at compile time what should remove the warnings.

Ever worse IMO, I am not a fan of that kind of "magic" because will it ever break it would be impossible to debug

> What exactly?

Not having spacing around qual signs

Not marking variables as final if they don't change

Not putting spaces on brackets with if-statements etc

Having your multi-catch block super condensed making it hard to read

Using that second for-loop when you can just use a stream to map it for that

Those for-loops doing the null checks

**Pull request closed without merging**
